import { useEffect, useMemo, useRef, useState } from 'react';
import { CloudDownload, CloudUpload, Database, Download, FileUp, HelpCircle, LogIn, LogOut, Pencil, Plus, RefreshCw, Search, Trash2, Upload, X } from 'lucide-react';
import * as XLSX from 'xlsx'; import { deleteRecord, getMeta, getRecords, putRecord, replaceRecords, setMeta } from './db'; import { download, login, logout, upload } from './google'; import { emptyRecord, type ErrorCode, type SyncMeta } from './types';
const fields:[keyof ErrorCode,string][]=[['code','エラーコード'],['name','名称'],['category','分類'],['type','タイプ'],['level','レベル'],['className','クラス'],['description','異常内容'],['investigation','調査内容'],['recovery','復旧方法'],['retry','Retry']];
const headers:Record<string,keyof ErrorCode>={'エラーコード':'code','名称':'name','分類':'category','タイプ':'type','レベル':'level','クラス':'className','異常内容':'description','調査内容':'investigation','復旧方法':'recovery','Retry':'retry'};
const fmt=(v?:string)=>v?new Intl.DateTimeFormat('ja-JP',{dateStyle:'short',timeStyle:'short'}).format(new Date(v)):'未同期';
export default function App(){
 const [records,setRecords]=useState<ErrorCode[]>([]),[meta,setSync]=useState<SyncMeta>({}),[online,setOnline]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [search,setSearch]=useState(''),[filters,setFilters]=useState({category:'',type:'',level:'',className:''}),[editing,setEditing]=useState<ErrorCode|null>(null); const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{Promise.all([getRecords(),getMeta()]).then(([r,m])=>{setRecords(r);setSync(m)})},[]);
 const options=(key:keyof typeof filters)=>[...new Set(records.map(r=>r[key]).filter(Boolean))].sort();
 const shown=useMemo(()=>records.filter(r=>{const q=search.toLowerCase();return (!q||fields.some(([k])=>String(r[k]).toLowerCase().includes(q)))&&Object.entries(filters).every(([k,v])=>!v||r[k as keyof ErrorCode]===v)}),[records,search,filters]);
 const act=async(fn:()=>Promise<void>)=>{setBusy(true);setMessage('');try{await fn()}catch(e){setMessage(e instanceof Error?e.message:'処理に失敗しました')}finally{setBusy(false)}};
 const save=()=>editing&&act(async()=>{if(!editing.code.trim())throw new Error('エラーコードは必須です');const v={...editing,code:String(editing.code),updatedAt:new Date().toISOString()};await putRecord(v);setRecords(p=>{const exists=p.some(x=>x.id===v.id);return exists?p.map(x=>x.id===v.id?v:x):[v,...p]});setEditing(null)});
 const remove=(r:ErrorCode)=>{if(confirm(`「${r.code} ${r.name}」を削除しますか？`))act(async()=>{await deleteRecord(r.id);setRecords(p=>p.filter(x=>x.id!==r.id))})};
 const signIn=()=>act(async()=>{await login();setOnline(true);setMessage('Google Driveに接続しました')});
 const cloudDown=()=>act(async()=>{if(!online)throw new Error('先にGoogleログインしてください');if(records.length&&!confirm('ローカルデータをクラウドの原本で置き換えますか？'))return;const d=await download();await replaceRecords(d.records);await setMeta(d.meta);setRecords(d.records);setSync(d.meta);setMessage('クラウドから最新データを取得しました')});
 const cloudUp=()=>act(async()=>{if(!online)throw new Error('先にGoogleログインしてください');const m=await upload(records,meta);await setMeta(m);setSync(m);setMessage('クラウドへ保存しました')});
 const exportData=(csv=false)=>{const data=records.map(r=>Object.fromEntries(fields.map(([k,l])=>[l,r[k]])));const ws=XLSX.utils.json_to_sheet(data);if(csv){const b=new Blob(['\ufeff'+XLSX.utils.sheet_to_csv(ws)],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='MachineErrorCodeDB.csv';a.click()}else{const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'エラーコード');XLSX.writeFile(wb,'MachineErrorCodeDB.xlsx')}};
 const importFile=(file:File)=>act(async()=>{const wb=XLSX.read(await file.arrayBuffer(),{type:'array',raw:true});const rows=XLSX.utils.sheet_to_json<Record<string,unknown>>(wb.Sheets[wb.SheetNames[0]],{defval:'',raw:false});const now=new Date().toISOString();const data=rows.map(row=>{const r=emptyRecord();Object.entries(headers).forEach(([h,k])=>r[k]=String(row[h]??'') as never);r.updatedAt=now;return r}).filter(r=>r.code);await replaceRecords(data);setRecords(data);setMessage(`${data.length}件をインポートしました`)});
 return <div><header><div className="brand"><span className="logo"><Database/></span><div><h1>機械エラーコード管理</h1><small>MACHINE ERROR CODE DATABASE</small></div></div><div className="header-actions"><span className={`status ${online?'ok':''}`}><i/> {online?'Google Drive 接続済み':'ローカルモード'} <b>最終同期 {fmt(meta.lastSyncedAt)}</b></span>{online?<button onClick={()=>{logout();setOnline(false)}}><LogOut/>ログアウト</button>:<button onClick={signIn}><LogIn/>Googleログイン</button>}<HelpCircle className="help"/></div></header>
 <main><section className="controls"><div className="filter-row"><label className="search"><span>キーワード検索</span><div><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="コード・名称・異常内容などを検索"/></div></label>{(['category','type','level','className'] as const).map(k=><label key={k}><span>{{category:'分類',type:'タイプ',level:'レベル',className:'クラス'}[k]}</span><select value={filters[k]} onChange={e=>setFilters({...filters,[k]:e.target.value})}><option value="">すべて</option>{options(k).map(v=><option key={v}>{v}</option>)}</select></label>)}</div><div className="action-row"><div><strong>エラーコード管理</strong><span className="count">{shown.length} / {records.length} 件</span></div><div className="buttons"><button onClick={cloudUp} disabled={busy}><CloudUpload/>クラウドへ保存</button><button onClick={cloudDown} disabled={busy}><CloudDownload/>クラウドから取得</button><button onClick={()=>exportData()}><Download/>Excel出力</button><button onClick={()=>exportData(true)}><Download/>CSV出力</button><button onClick={()=>input.current?.click()}><FileUp/>Excel / CSV取込</button><input ref={input} hidden type="file" accept=".xlsx,.xls,.csv" onChange={e=>{if(e.target.files?.[0])importFile(e.target.files[0]);e.target.value=''}}/></div></div></section>
 {message&&<div className="notice"><span>{message}</span><button onClick={()=>setMessage('')}><X/></button></div>}
 <section className="table-card"><div className="table-title"><div><h2>エラーコード一覧</h2><span>{shown.length}件</span></div><button className="primary" onClick={()=>setEditing(emptyRecord())}><Plus/>新規登録</button></div><div className="table-wrap"><table><thead><tr>{fields.map(([,l])=><th key={l}>{l}</th>)}<th>操作</th></tr></thead><tbody>{shown.length?shown.map(r=><tr key={r.id}>{fields.map(([k])=><td key={k} className={['description','investigation','recovery'].includes(k)?'long':k==='code'?'code':''}>{r[k]||<span className="empty">—</span>}</td>)}<td className="row-actions"><button title="編集" onClick={()=>setEditing({...r})}><Pencil/></button><button title="削除" onClick={()=>remove(r)}><Trash2/></button></td></tr>):<tr><td colSpan={11} className="no-data"><Database/><strong>エラーコードがありません</strong><span>「新規登録」またはファイル取込からデータを追加してください</span></td></tr>}</tbody></table></div></section></main>
 {editing&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setEditing(null)}><div className="modal"><div className="modal-head"><div><h2>{records.some(r=>r.id===editing.id)?'エラーコードを編集':'エラーコードを新規登録'}</h2><p>機械のエラー情報を入力してください</p></div><button onClick={()=>setEditing(null)}><X/></button></div><div className="form">{fields.map(([k,l])=><label key={k} className={['description','investigation','recovery'].includes(k)?'wide':''}><span>{l}{k==='code'&&<em>必須</em>}</span>{['description','investigation','recovery'].includes(k)?<textarea rows={3} value={editing[k]} onChange={e=>setEditing({...editing,[k]:e.target.value})}/>:<input value={editing[k]} onChange={e=>setEditing({...editing,[k]:e.target.value})} placeholder={k==='code'?'例: E001、AL-12':''}/>}</label>)}</div><div className="modal-foot"><button onClick={()=>setEditing(null)}>キャンセル</button><button className="primary" onClick={save} disabled={busy}><Upload/>保存する</button></div></div></div>} {busy&&<div className="busy"><RefreshCw/>処理中...</div>}</div>
}
