import { useEffect, useMemo, useRef, useState } from 'react';
import { CloudDownload, CloudUpload, Database, Download, FileSpreadsheet, FileUp, HelpCircle, LogIn, LogOut, Pencil, Plus, RefreshCw, Search, Trash2, Upload, X } from 'lucide-react';
import * as XLSX from 'xlsx'; import BrandMark from './BrandMark'; import { deleteRecord, getMeta, getRecords, putRecord, replaceRecords, setMeta } from './db'; import { download, login, logout, upload } from './google'; import { emptyRecord, MACHINE_MODELS, type DataScope, type ErrorCode, type MachineModel, type MachineSeries, type SyncMeta } from './types';
const fields:[keyof ErrorCode,string][]=[['code','エラーコード'],['name','名称'],['category','分類'],['type','タイプ'],['level','レベル'],['className','クラス'],['description','異常内容'],['investigation','調査内容'],['recovery','復旧方法'],['retry','Retry']];
const headers:Record<string,keyof ErrorCode>={'エラーコード':'code','名称':'name','分類':'category','タイプ':'type','レベル':'level','クラス':'className','異常内容':'description','調査内容':'investigation','復旧方法':'recovery','Retry':'retry'};
const fmt=(v?:string)=>v?new Intl.DateTimeFormat('ja-JP',{dateStyle:'short',timeStyle:'short'}).format(new Date(v)):'未同期';
export default function App(){
 const [records,setRecords]=useState<ErrorCode[]>([]),[meta,setSync]=useState<SyncMeta>({}),[online,setOnline]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [series,setSeries]=useState<MachineSeries>('SRC350'),[model,setModel]=useState<MachineModel>('SRC350-M2'),[search,setSearch]=useState(''),[filters,setFilters]=useState({code:'',category:'',type:'',level:'',className:''}),[editing,setEditing]=useState<ErrorCode|null>(null),[importOpen,setImportOpen]=useState(false),[importScope,setImportScope]=useState<DataScope>('series'),[dragging,setDragging]=useState(false); const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{Promise.all([getRecords(),getMeta()]).then(([r,m])=>{setRecords(r);setSync(m)})},[]);
 const machineRecords=useMemo(()=>records.filter(r=>r.series===series&&(r.scope==='series'||r.model===model)),[records,series,model]);
 const options=(key:keyof typeof filters)=>[...new Set(machineRecords.map(r=>r[key]).filter(Boolean))].sort();
 const shown=useMemo(()=>machineRecords.filter(r=>{const q=search.toLowerCase();return (!q||fields.some(([k])=>String(r[k]).toLowerCase().includes(q)))&&Object.entries(filters).every(([k,v])=>!v||r[k as keyof ErrorCode]===v)}),[machineRecords,search,filters]);
 const act=async(fn:()=>Promise<void>)=>{setBusy(true);setMessage('');try{await fn()}catch(e){setMessage(e instanceof Error?e.message:'処理に失敗しました')}finally{setBusy(false)}};
 const save=()=>editing&&act(async()=>{if(!editing.code.trim())throw new Error('エラーコードは必須です');const v={...editing,code:String(editing.code),updatedAt:new Date().toISOString()};await putRecord(v);setRecords(p=>{const exists=p.some(x=>x.id===v.id);return exists?p.map(x=>x.id===v.id?v:x):[v,...p]});setEditing(null)});
 const remove=(r:ErrorCode)=>{if(confirm(`「${r.code} ${r.name}」を削除しますか？`))act(async()=>{await deleteRecord(r.id);setRecords(p=>p.filter(x=>x.id!==r.id))})};
 const signIn=()=>act(async()=>{await login();setOnline(true);setMessage('Google Driveに接続しました')});
 const cloudDown=()=>act(async()=>{if(!online)throw new Error('先にGoogleログインしてください');if(records.length&&!confirm('ローカルデータをクラウドの原本で置き換えますか？'))return;const d=await download();await replaceRecords(d.records);await setMeta(d.meta);setRecords(d.records);setSync(d.meta);setMessage('クラウドから最新データを取得しました')});
 const cloudUp=()=>act(async()=>{if(!online)throw new Error('先にGoogleログインしてください');const m=await upload(records,meta);await setMeta(m);setSync(m);setMessage('クラウドへ保存しました')});
 const exportData=()=>{const data=machineRecords.map(r=>Object.fromEntries(fields.map(([k,l])=>[l,r[k]])));const ws=XLSX.utils.json_to_sheet(data);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'エラーコード');XLSX.writeFile(wb,`MachineErrorCodeDB-${model}.xlsx`)};
 const downloadTemplate=()=>{const ws=XLSX.utils.aoa_to_sheet([fields.map(([,label])=>label)]);ws['!cols']=fields.map(([key])=>({wch:['description','investigation','recovery'].includes(key)?32:key==='code'?16:14}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'インポート');XLSX.writeFile(wb,`MachineErrorCodeDB-${model}-import-template.xlsx`)};
 const importFile=(file:File)=>act(async()=>{const wb=XLSX.read(await file.arrayBuffer(),{type:'array',raw:true});const sheet=wb.Sheets[wb.SheetNames[0]];const rows=XLSX.utils.sheet_to_json<Record<string,unknown>>(sheet,{defval:'',raw:false});const firstRow=XLSX.utils.sheet_to_json<string[]>(sheet,{header:1,defval:'',raw:false})[0]||[];if(!firstRow.includes('エラーコード'))throw new Error('「エラーコード」列がありません。インポート用フォーマットを使用してください。');const now=new Date().toISOString();const targeted=records.filter(r=>r.series===series&&r.scope===importScope&&(importScope==='series'||r.model===model));const byCode=new Map(targeted.map(r=>[r.code,r]));let added=0,updated=0,skipped=0;for(const row of rows){const code=String(row['エラーコード']??'').trim();if(!code){skipped++;continue}const existing=byCode.get(code);const value=existing?{...existing}:{...emptyRecord(series,model,importScope),code};Object.entries(headers).forEach(([heading,key])=>value[key]=String(row[heading]??'') as never);value.code=code;value.scope=importScope;value.updatedAt=now;byCode.set(code,value);if(existing)updated++;else added++}const untouched=records.filter(r=>!(r.series===series&&r.scope===importScope&&(importScope==='series'||r.model===model)));const all=[...untouched,...byCode.values()];await replaceRecords(all);setRecords(all);setImportOpen(false);setMessage(`${importScope==='series'?'シリーズ共通':'型式固有'}: 新規 ${added}件、更新 ${updated}件、スキップ ${skipped}件を読み込みました`)});
 return <div><header><div className="brand"><span className="logo"><BrandMark/></span><div><h1>機械エラーコード管理</h1><small>MACHINE ERROR CODE DATABASE</small></div></div><div className="header-actions"><span className={`status ${online?'ok':''}`}><i/> {online?'Google Drive 接続済み':'ローカルモード'} <b>最終同期 {fmt(meta.lastSyncedAt)}</b></span>{online?<button onClick={()=>{logout();setOnline(false)}}><LogOut/>ログアウト</button>:<button onClick={signIn}><LogIn/>Googleログイン</button>}<HelpCircle className="help"/></div></header>
 <main><section className="controls"><div className="filter-row"><label><span>シリーズ</span><select value={series} onChange={e=>{const next=e.target.value as MachineSeries;setSeries(next);setModel(MACHINE_MODELS[next][0]);setFilters({code:'',category:'',type:'',level:'',className:''});setSearch('')}}>{(Object.keys(MACHINE_MODELS) as MachineSeries[]).map(v=><option key={v}>{v}</option>)}</select></label><label><span>型式</span><select value={model} onChange={e=>{setModel(e.target.value as MachineModel);setFilters({code:'',category:'',type:'',level:'',className:''});setSearch('')}}>{MACHINE_MODELS[series].map(v=><option key={v}>{v}</option>)}</select></label><label><span>エラーコード</span><select value={filters.code} onChange={e=>setFilters({...filters,code:e.target.value})}><option value="">すべて</option>{options('code').map(v=><option key={v}>{v}</option>)}</select></label><label className="search"><span>キーワード検索</span><div><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="コード・名称・異常内容などを検索"/></div></label>{(['category','type','level','className'] as const).map(k=><label key={k}><span>{{category:'分類',type:'タイプ',level:'レベル',className:'クラス'}[k]}</span><select value={filters[k]} onChange={e=>setFilters({...filters,[k]:e.target.value})}><option value="">すべて</option>{options(k).map(v=><option key={v}>{v}</option>)}</select></label>)}</div><div className="action-row"><div><strong>{series}</strong><span className="machine-separator">›</span><strong className="model-badge">{model}</strong><span className="count">{shown.length} / {machineRecords.length} 件</span></div><div className="buttons"><button onClick={cloudUp} disabled={busy}><CloudUpload/>クラウドへ保存</button><button onClick={cloudDown} disabled={busy}><CloudDownload/>クラウドから取得</button><button onClick={exportData}><Download/>Excel出力</button><button onClick={()=>setImportOpen(true)}><FileUp/>Excel / CSV取込</button></div></div></section>
 {message&&<div className="notice"><span>{message}</span><button onClick={()=>setMessage('')}><X/></button></div>}
 <section className="table-card"><div className="table-title"><div><h2>{model} エラーコード一覧</h2><span>{shown.length}件</span></div><button className="primary" onClick={()=>setEditing(emptyRecord(series,model))}><Plus/>新規登録</button></div><div className="table-wrap"><table><thead><tr>{fields.map(([,l])=><th key={l}>{l}</th>)}<th>操作</th></tr></thead><tbody>{shown.length?shown.map(r=><tr key={r.id}>{fields.map(([k])=><td key={k} className={['description','investigation','recovery'].includes(k)?'long':k==='code'?'code':''}>{r[k]||<span className="empty">—</span>}</td>)}<td className="row-actions"><button title="編集" onClick={()=>setEditing({...r})}><Pencil/></button><button title="削除" onClick={()=>remove(r)}><Trash2/></button></td></tr>):<tr><td colSpan={11} className="no-data"><Database/><strong>エラーコードがありません</strong><span>「新規登録」またはファイル取込からデータを追加してください</span></td></tr>}</tbody></table></div></section></main>
 {importOpen&&<div className="overlay import-overlay" onMouseDown={e=>e.target===e.currentTarget&&setImportOpen(false)}><div className="import-modal"><div className="import-head"><span className="import-icon"><FileSpreadsheet/></span><button onClick={()=>setImportOpen(false)}><X/></button></div><h2>Excel / CSV インポート</h2><p className="import-target">対象：<b>{series} / {model}</b></p><button className="template-button" onClick={downloadTemplate}><Download/>インポート用ExcelフォーマットをDL</button><div className="popup-rules"><strong>取り込みルール</strong><ul><li><b>主キー：</b>エラーコードを対象範囲内で照合します。</li><li><b>既存コード：</b>選択した登録先の内容で上書きします。</li><li><b>新規コード：</b>新しい行として追加します。</li><li><b>空白セル：</b>空文字として登録し、既存値も空白で上書きします。</li><li><b>コードが空の行：</b>読み飛ばします。</li><li><b>同一コード：</b>ファイル内で後にある行を採用します。</li></ul></div><div className="scope-options"><label><input type="radio" name="scope" checked={importScope==='series'} onChange={()=>setImportScope('series')}/><span><b>シリーズ共通データ</b><small>{series}の全型式で表示</small></span></label><label><input type="radio" name="scope" checked={importScope==='model'} onChange={()=>setImportScope('model')}/><span><b>型式固有データ</b><small>{model}だけで表示</small></span></label></div><div className={`drop-zone ${dragging?'dragging':''}`} onClick={()=>input.current?.click()} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);if(e.dataTransfer.files[0])importFile(e.dataTransfer.files[0])}}><CloudUpload/><strong>ファイルをドロップ</strong><span>またはクリックして選択</span><small>.xlsx / .xls / .csv（先頭シートを読み込み）</small></div><input ref={input} hidden type="file" accept=".xlsx,.xls,.csv" onChange={e=>{if(e.target.files?.[0])importFile(e.target.files[0]);e.target.value='' }}/></div></div>}
 {editing&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setEditing(null)}><div className="modal"><div className="modal-head"><div><h2>{records.some(r=>r.id===editing.id)?'エラーコードを編集':'エラーコードを新規登録'}</h2><p>{editing.series} / {editing.model} のエラー情報を入力してください</p></div><button onClick={()=>setEditing(null)}><X/></button></div><div className="form">{fields.map(([k,l])=><label key={k} className={['description','investigation','recovery'].includes(k)?'wide':''}><span>{l}{k==='code'&&<em>必須</em>}</span>{['description','investigation','recovery'].includes(k)?<textarea rows={3} value={editing[k]} onChange={e=>setEditing({...editing,[k]:e.target.value})}/>:<input value={editing[k]} onChange={e=>setEditing({...editing,[k]:e.target.value})} placeholder={k==='code'?'例: E001、AL-12':''}/>}</label>)}</div><div className="modal-foot"><button onClick={()=>setEditing(null)}>キャンセル</button><button className="primary" onClick={save} disabled={busy}><Upload/>保存する</button></div></div></div>} {busy&&<div className="busy"><RefreshCw/>処理中...</div>}</div>
}
