import { normalizeRecord, type ErrorCode, type SyncMeta } from './types';
const FILE='MachineErrorCodeDB-latest.json'; const SCOPE='https://www.googleapis.com/auth/drive.file';
let token='';
declare global { interface Window { google?: { accounts:{oauth2:{initTokenClient:(o:Record<string,unknown>)=>{requestAccessToken:()=>void};revoke:(t:string,cb:()=>void)=>void}}}} }
const loadScript=()=>new Promise<void>((resolve,reject)=>{if(window.google)return resolve();const s=document.createElement('script');s.src='https://accounts.google.com/gsi/client';s.onload=()=>resolve();s.onerror=()=>reject(new Error('Google認証の読み込みに失敗しました'));document.head.appendChild(s)});
export async function login(){await loadScript();const clientId=import.meta.env.VITE_GOOGLE_CLIENT_ID;if(!clientId)throw new Error('VITE_GOOGLE_CLIENT_ID が設定されていません');return new Promise<void>((resolve,reject)=>window.google!.accounts.oauth2.initTokenClient({client_id:clientId,scope:SCOPE,callback:(r:unknown)=>{const x=r as {access_token?:string;error?:string};if(x.error)reject(new Error(x.error));else{token=x.access_token!;resolve()}}}).requestAccessToken())}
export function logout(){if(token)window.google?.accounts.oauth2.revoke(token,()=>{});token=''}
async function api(url:string,init?:RequestInit){const r=await fetch(url,{...init,headers:{Authorization:`Bearer ${token}`,...init?.headers}});if(!r.ok)throw new Error(`Google Drive API エラー (${r.status})`);return r}
export async function findFile(){const q=encodeURIComponent(`name='${FILE}' and trashed=false`);const r=await api(`https://www.googleapis.com/drive/v3/files?q=${q}&fields=files(id,modifiedTime)&spaces=drive`);return ((await r.json()).files as {id:string;modifiedTime:string}[])[0]}
export async function download(){const f=await findFile();if(!f)throw new Error(`${FILE} が見つかりません`);const r=await api(`https://www.googleapis.com/drive/v3/files/${f.id}?alt=media`);const data=await r.json() as Partial<ErrorCode>[];return {records:data.map(normalizeRecord),meta:{fileId:f.id,cloudModifiedTime:f.modifiedTime,lastSyncedAt:new Date().toISOString()} as SyncMeta}}
export async function upload(records:ErrorCode[],meta:SyncMeta){const current=await findFile();if(current&&!meta.cloudModifiedTime)throw new Error('クラウドに原本があります。上書き防止のため、先に「クラウドから取得」を実行してください。');if(current&&current.modifiedTime!==meta.cloudModifiedTime)throw new Error('別の端末でクラウドが更新されています。先に「クラウドから取得」を実行してください。');const body=JSON.stringify(records,null,2);let response:Response;if(current){response=await api(`https://www.googleapis.com/upload/drive/v3/files/${current.id}?uploadType=media&fields=id,modifiedTime`,{method:'PATCH',headers:{'Content-Type':'application/json'},body})}else{const boundary='machine-error-boundary';const multipart=`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify({name:FILE,mimeType:'application/json'})}\r\n--${boundary}\r\nContent-Type: application/json\r\n\r\n${body}\r\n--${boundary}--`;response=await api('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,modifiedTime',{method:'POST',headers:{'Content-Type':`multipart/related; boundary=${boundary}`},body:multipart})}const f=await response.json();return {fileId:f.id,cloudModifiedTime:f.modifiedTime,lastSyncedAt:new Date().toISOString()} as SyncMeta}
